### ISSUE TITLE
support for converstion

### ISSUE THREAD

**Issue by leinemann** [fivetran/dbt_ad_reporting#14]
Hi there, has anyone considered the addition of conversions to ad_reporting?  Are there existing considerations/complications/work that's already started?  I would be curious to understand how difficult it would be to add them and happy to contribute if that's an option. 
Please let me know your thoughts.
many thanks,
Christoph.

**Comment by fivetran-kristin** [comment]
Hey Christoph 👋 - thanks for this question.  Here are our thoughts in regards to adding converstion metrics:

- Many of the platforms have multiple different conversion metrics and there isn’t a lot of consistency as to which metrics different customers will care about. We would need to only use one conversion metric so that the columns can be unioned together, and the choice of multiple metrics therefore causes us a problem.
- The conversion metrics from each ad platform are self-reported by the ad platforms themselves. They use their own attribution models, which (obviously) are generous to themselves. Once you union all the data together, if you were to sum the number of conversion on a given day, you would end up with a much larger number of conversion than actually happened in reality, because the same conversion might be included in multiple different ad platforms. We would prefer people decide and use their own attribution models and combine it with the data we provide, rather than using the conversion from the ad platforms.


Very curious to hear your thoughts on this.
